# docker-compose.yml
version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "80:3000"
    restart: always 
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGREST_MAX_ROWS: 10000
