# Build and push docker image with production **and** staging tags
name: Docker Image CI

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/atd-knack-services:production
            ${{ secrets.DOCKER_USERNAME }}/atd-knack-services:staging
            ${{ secrets.DOCKER_USERNAME }}/atd-knack-services:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
